# Generated by Django 4.1.7 on 2023-06-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="event_photos")),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField(max_length=1000)),
            ],
        ),
    ]
