# Generated by Django 4.1.7 on 2023-06-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0002_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="location",
            field=models.TextField(default="IU Auditorium", max_length=100),
        ),
        migrations.AlterField(
            model_name="event",
            name="time",
            field=models.CharField(max_length=300),
        ),
    ]
