# Generated by Django 4.1.7 on 2023-06-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0003_event_location_alter_event_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="event_photos")),
                ("name", models.CharField(max_length=300)),
                ("title", models.CharField(max_length=300)),
            ],
        ),
    ]
