# Generated by Django 4.1.7 on 2023-06-07 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0004_team"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TeamMember",
        ),
    ]
