# Generated by Django 4.1.7 on 2023-06-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0005_delete_teammember"),
    ]

    operations = [
        migrations.CreateModel(
            name="Upcomming_event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("date", models.DateField()),
                ("time", models.CharField(max_length=300)),
                ("location", models.CharField(default="IU Auditorium", max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(max_length=300),
        ),
    ]
