# Generated by Django 4.1.7 on 2023-06-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0007_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="message",
            field=models.TextField(max_length=1000),
        ),
    ]
