# Generated by Django 4.1.7 on 2023-06-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0010_alter_contact_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="message",
            field=models.CharField(default=" ", max_length=1000, null=True),
        ),
    ]
